### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by coolcaper777** [Colorado4Wheeler/Mac-Commander#1]
Hi,
While enabling the plug in I get this error:

Loading plugin "EPS - Mac Commander 2.0.0-b4"
   Starting plugin "EPS - Mac Commander 2.0.0-b4" (pid 56789)
   EPS - Mac Commander Error       Error in plugin execution InitializeMain:

Traceback (most recent call last):
  File "plugin.py", line 35, in <module>
ImportError: No module named psutil

   Stopping plugin "EPS - Mac Commander 2.0.0-b4" (pid 56789)
   Stopped plugin "EPS - Mac Commander 2.0.0-b4"

**Comment by Colorado4Wheeler** [comment]
I'm not sure why that didn't happen when I released it but I can see it's a bug.  That was a test library anyway, psutil.  I was able to easily reproduce the error on a clean install.

If you feel comfortable editing the plugin.py file you can comment it out and everything else should be fine (beta 5 is in limbo, it would break on your end if I uploaded it right now).

Just put a # in front of the two marked lines in plugin.py (starts about line 23 or so).

	#sys.path.append('lib/psutil') <<-------------------
	import indigo
	from lib.pexpect import pxssh
	#import psutil <<-------------------

**Comment by coolcaper777** [comment]
Will do, thanks. Will report back.

**Comment by coolcaper777** [comment]
Working now. Thanks.
